### PR TITLE
fix: add message when there is no web3

### PR DESCRIPTION
**Pull request by eburgos**
Added a message when there is no Metamask installed in your browser. Requested by issue #129

### CODE REVIEW

**Comment by eburgos** [comment]
Lint passes well @epiqueras

**Comment by epiqueras** [comment]
I tested on incognito mode (no web3), and it still passes the first `if` statement after it fails to fetch:

https://github.com/kleros/kleros-juror-front/blob/0e21058800019280a46ef5bb27937a0cd1b948c3/src/bootstrap/initializer.js#L42

So I added the `if` guard here:

https://github.com/kleros/kleros-juror-front/blob/0e21058800019280a46ef5bb27937a0cd1b948c3/src/bootstrap/initializer.js#L43

**Comment by eburgos** [comment]
do I need to do something?

**Comment by epiqueras** [comment]
No, all good.

**Pull request closed without merging**
