### PR TITLE
fix: add message when there is no web3 - issue #129

### PR DESCRIPTION
**Pull request by eburgos**
Added a message when there is no Metamask installed in your browser. Requested by issue #129

### CODE REVIEW

**Comment by eburgos** [comment]
@epiqueras I tested with a browser with metamask unlocked, locked and no metamask.  How does my metamask need to be configured to get the "Loading" state? Do I need to have multiple accounts?

**Comment by epiqueras** [comment]
Loading happens because the accounts are fetched asynchronously. See `accounts.loading`, in that case you are also showing the `RequiresMetaMask` component, even though they might have MetaMask, but the request is still loading.

**Comment by eburgos** [comment]
Yes, I now see what you mean.

**Comment by eburgos** [comment]
Could that work @epiqueras ? Tested with metamask and shows Loading... then with no metamask and shows the download one.

**Comment by epiqueras** [comment]
That works. Please fix linting errors and submit the PR against the `develop` branch.

**Pull request closed without merging**
